### YamlMime:ManagedReference
items:
- uid: ASE_Assignment_Test_Project.GloabalConfigTest
  commentId: T:ASE_Assignment_Test_Project.GloabalConfigTest
  id: GloabalConfigTest
  parent: ASE_Assignment_Test_Project
  children:
  - ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetIsFillEnabled
  - ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxX
  - ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxY
  - ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetPenSize
  langs:
  - csharp
  - vb
  name: GloabalConfigTest
  nameWithType: GloabalConfigTest
  fullName: ASE_Assignment_Test_Project.GloabalConfigTest
  type: Class
  source:
    remote:
      path: ASE_Sumit_Kasula_77356748/ASE-Assignment-Test-Project/GloabalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-SUMITKASULA.git
    id: GloabalConfigTest
    path: ASE-Assignment-Test-Project/GloabalConfigTest.cs
    startLine: 13
  assemblies:
  - ASE-Assignment-Test-Project
  namespace: ASE_Assignment_Test_Project
  summary: Unit tests for the GlobalConfig class.
  example: []
  syntax:
    content: >-
      [TestClass]

      public class GloabalConfigTest
    content.vb: >-
      <TestClass>

      Public Class GloabalConfigTest
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute.#ctor
    arguments: []
- uid: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxX
  commentId: M:ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxX
  id: TestSetAndGetMaxX
  parent: ASE_Assignment_Test_Project.GloabalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetMaxX()
  nameWithType: GloabalConfigTest.TestSetAndGetMaxX()
  fullName: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxX()
  type: Method
  source:
    remote:
      path: ASE_Sumit_Kasula_77356748/ASE-Assignment-Test-Project/GloabalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-SUMITKASULA.git
    id: TestSetAndGetMaxX
    path: ASE-Assignment-Test-Project/GloabalConfigTest.cs
    startLine: 19
  assemblies:
  - ASE-Assignment-Test-Project
  namespace: ASE_Assignment_Test_Project
  summary: Tests setting and getting the MaxX property.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetMaxX()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetMaxX()
  overload: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxX*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
- uid: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxY
  commentId: M:ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxY
  id: TestSetAndGetMaxY
  parent: ASE_Assignment_Test_Project.GloabalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetMaxY()
  nameWithType: GloabalConfigTest.TestSetAndGetMaxY()
  fullName: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxY()
  type: Method
  source:
    remote:
      path: ASE_Sumit_Kasula_77356748/ASE-Assignment-Test-Project/GloabalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-SUMITKASULA.git
    id: TestSetAndGetMaxY
    path: ASE-Assignment-Test-Project/GloabalConfigTest.cs
    startLine: 35
  assemblies:
  - ASE-Assignment-Test-Project
  namespace: ASE_Assignment_Test_Project
  summary: Tests setting and getting the MaxY property.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetMaxY()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetMaxY()
  overload: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxY*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
- uid: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetIsFillEnabled
  commentId: M:ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetIsFillEnabled
  id: TestSetAndGetIsFillEnabled
  parent: ASE_Assignment_Test_Project.GloabalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetIsFillEnabled()
  nameWithType: GloabalConfigTest.TestSetAndGetIsFillEnabled()
  fullName: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetIsFillEnabled()
  type: Method
  source:
    remote:
      path: ASE_Sumit_Kasula_77356748/ASE-Assignment-Test-Project/GloabalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-SUMITKASULA.git
    id: TestSetAndGetIsFillEnabled
    path: ASE-Assignment-Test-Project/GloabalConfigTest.cs
    startLine: 51
  assemblies:
  - ASE-Assignment-Test-Project
  namespace: ASE_Assignment_Test_Project
  summary: Tests setting and getting the IsFillEnabled property.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetIsFillEnabled()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetIsFillEnabled()
  overload: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetIsFillEnabled*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
- uid: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetPenSize
  commentId: M:ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetPenSize
  id: TestSetAndGetPenSize
  parent: ASE_Assignment_Test_Project.GloabalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetPenSize()
  nameWithType: GloabalConfigTest.TestSetAndGetPenSize()
  fullName: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetPenSize()
  type: Method
  source:
    remote:
      path: ASE_Sumit_Kasula_77356748/ASE-Assignment-Test-Project/GloabalConfigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-SUMITKASULA.git
    id: TestSetAndGetPenSize
    path: ASE-Assignment-Test-Project/GloabalConfigTest.cs
    startLine: 67
  assemblies:
  - ASE-Assignment-Test-Project
  namespace: ASE_Assignment_Test_Project
  summary: Tests setting and getting the PenSize property.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetPenSize()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetPenSize()
  overload: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetPenSize*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
references:
- uid: ASE_Assignment_Test_Project
  commentId: N:ASE_Assignment_Test_Project
  href: ASE_Assignment_Test_Project.html
  name: ASE_Assignment_Test_Project
  nameWithType: ASE_Assignment_Test_Project
  fullName: ASE_Assignment_Test_Project
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxX*
  commentId: Overload:ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxX
  href: ASE_Assignment_Test_Project.GloabalConfigTest.html#ASE_Assignment_Test_Project_GloabalConfigTest_TestSetAndGetMaxX
  name: TestSetAndGetMaxX
  nameWithType: GloabalConfigTest.TestSetAndGetMaxX
  fullName: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxX
- uid: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxY*
  commentId: Overload:ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxY
  href: ASE_Assignment_Test_Project.GloabalConfigTest.html#ASE_Assignment_Test_Project_GloabalConfigTest_TestSetAndGetMaxY
  name: TestSetAndGetMaxY
  nameWithType: GloabalConfigTest.TestSetAndGetMaxY
  fullName: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetMaxY
- uid: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetIsFillEnabled*
  commentId: Overload:ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetIsFillEnabled
  href: ASE_Assignment_Test_Project.GloabalConfigTest.html#ASE_Assignment_Test_Project_GloabalConfigTest_TestSetAndGetIsFillEnabled
  name: TestSetAndGetIsFillEnabled
  nameWithType: GloabalConfigTest.TestSetAndGetIsFillEnabled
  fullName: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetIsFillEnabled
- uid: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetPenSize*
  commentId: Overload:ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetPenSize
  href: ASE_Assignment_Test_Project.GloabalConfigTest.html#ASE_Assignment_Test_Project_GloabalConfigTest_TestSetAndGetPenSize
  name: TestSetAndGetPenSize
  nameWithType: GloabalConfigTest.TestSetAndGetPenSize
  fullName: ASE_Assignment_Test_Project.GloabalConfigTest.TestSetAndGetPenSize
